import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    imgLink: '/images/DatabaseImage/61Iz2yy2CKL.jpg',
    price: "1780",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "Traitors Gate (William Warwick Novels)",
    author: "Jeffrey Archer",
    imgLink: '/images/DatabaseImage/714JNsODlGL.jpg',
    price: "5000",
    categoryName: "Crime",
  },
  {
    _id: uuid(),
    title: "Sudoku",
    author: "Wonder House Books",
    imgLink: '/images/DatabaseImage/81AmIToXvnL.jpg',
    price: "3990",
    categoryName: "Educational",
  },
  {
    _id: uuid(),
    title: "Object-Oriented Programming with C++ | 8th Edition",
    author: " E Balagurusamy",
    imgLink: '/images/DatabaseImage/61ynRHlKuML.jpg',
    price: "6370",
    categoryName: "Educational",
  },
  {
    _id: uuid(),
    title: "Enemy At The Gates",
    author: "Vince Flynn and Kyle Mills ",
    imgLink: '/images/DatabaseImage/81ZTSrbHimL.jpg',
    price: "3320",
    categoryName: "Crime",
  },
  {
    _id: uuid(),
    title: "Pride & Prejudice (Deluxe Hardbound Edition)",
    author: "Jane Austen",
    imgLink: '/images/DatabaseImage/81WF2uHdxiS.jpg',
    price: "4790",
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    title: "Think Straight: Change your thoughts, Change your life",
    author: " Darius Foroux",
    imgLink: '/images/DatabaseImage/71Yb9hJXocL.jpg',
    price: "1090",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "GATE 2024 Electrical Engineering",
    author: "ACE Engineering Academy",
    imgLink: '/images/DatabaseImage/51jc5F0iz4L.jpg',
    price: "6800",
    categoryName: "Educational",
  },
  {
    _id: uuid(),
    title: "Harry Potter Box Set: The Complete Collection",
    author: "J.K. Rowling",
    imgLink: '/images/DatabaseImage/81zqe4fNdlL.jpg',
    price: "25000",
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    title: "The Complete Novels of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    imgLink: '/images/DatabaseImage/71WZEX98qdL.jpg',
    price: "2500",
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    title: "JAVA: THE COMPLETE REFERENCE ,12TH EDITION",
    author: "Herbert Schildt ",
    imgLink: '/images/DatabaseImage/771AF8eZ5A5L.jpg',
    price: "12800",
    categoryName: "Educational",
  },
  {
    _id: uuid(),
    title: "Don't Believe Everything You Think",
    author: " Joseph Nguyen",
    imgLink: '/images/DatabaseImage/716w5Xpj8L.jpg',
    price: "2900",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "Death Beyond Forbidding Gates",
    author: "Sarah Pinborough ",
    imgLink: '/images/DatabaseImage/51j6rhjFL6S.jpg',
    price: "5930",
    categoryName: "Crime",
  },
  {
    _id: uuid(),
    title: "Rich Dad Poor Dad",
    author: " Robert T. Kiyosaki",
    imgLink: '/images/DatabaseImage/81BE7eeKzAL.jpg',
    price: "6000",
    categoryName: "Development",
  },
  {
    _id: uuid(),
    title: "Night Train at Deoli and Other Stories",
    author: "Ruskin Bond ",
    imgLink: '/images/DatabaseImage/81APABLp4wS.jpg',
    price: "4050",
    categoryName: "Fiction",
  },
  {
    _id: uuid(),
    title: "Gates' Bookstore: 1",
    author: "Jamila A Stone",
    imgLink: '/images/DatabaseImage/61DWEmqBkeL.jpg',
    price: "9000",
    categoryName: "Crime",
  },
];
