// import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
      _id: "76e04bd5-fa42-427c-9574-147dbc7e7a4f",
      title: "The Monk Who Sold His Ferrari",
      author: "Robin Sharma",
      imgLink: "/images/DatabaseImage/61Iz2yy2CKL.jpg",
      price: 1780,
      categoryName: ["Development"],
      description: "Curabitur pulvinar nisi sed augue congue, id maximus risus sollicitudin. Nulla accumsan orci nec sodales ullamcorper.",
      id: 1,
      rating: 4.6
  },
  {
      _id: "a3eae556-3b7d-443b-8042-b0a3e8b35c81",
      title: "Traitors Gate (William Warwick Novels)",
      author: "Jeffrey Archer",
      imgLink: "/images/DatabaseImage/714JNsODlGL.jpg",
      price: 5000,
      categoryName: ["Crime"],
      description: "Etiam non dui sit amet magna blandit mattis ut at turpis. Duis vehicula enim et diam euismod, non fringilla libero efficitur.",
      id: 2,
      rating: 4,
  },
  {
      _id: "301670db-7173-489d-acd1-968576278bcf",
      title: "Sudoku",
      author: "Wonder House Books",
      imgLink: "/images/DatabaseImage/81AmIToXvnL.jpg",
      price: 3990,
      categoryName: ["Educational", "Development"],
      description: "Aliquam pulvinar nunc quis elit aliquam malesuada.Nulla ollisnibh consequat mauris varius, eget vehicula arcu commodo.",
      id: 3,
      rating: 2,
  },
  {
      _id: "db68b03c-380a-4ccf-b3c5-035263c969a2",
      title: "Object-Oriented Programming with C++ | 8th Edition",
      author: " E Balagurusamy",
      imgLink: "/images/DatabaseImage/61ynRHlKuML.jpg",
      price: 6370,
      categoryName: ["Educational", "Crime"],
      description: "Cras quis velit imperdiet, cursus purus quis, luctus est. Cras vitae neque sit amet lorem fermentum dapibus.",
      id: 4,
      rating: 4.8
  },
  {
      _id: "1aa3c52f-8576-4458-9bef-e585097af911",
      title: "Enemy At The Gates",
      author: "Vince Flynn and Kyle Mills ",
      imgLink: "/images/DatabaseImage/81ZTSrbHimL.jpg",
      price: 3320,
      categoryName: ["Crime", "Development", "Fiction"],
      description: "Nullam sed dui ut dui ultrices tincidunt. Nullam condimentum lorem eu tellus pellentesque pellentesque.",
      id: 5,
      rating: 4,
  },
  {
      _id: "299cc1ab-9889-40dc-a3e2-944c4afd74c5",
      title: "Pride & Prejudice (Deluxe Hardbound Edition)",
      author: "Jane Austen",
      imgLink: "/images/DatabaseImage/81WF2uHdxiS.jpg",
      price: 4790,
      categoryName: ["Fiction", "Development"],
      description: "Curabitur accumsan tellus bibendum, posuere arcu sit amet, rutrum purus. Donec non tortor sed risus sodales efficitur.",
      id: 6,
      rating: 2,
  },
  {
      _id: "f10c36f2-c7fd-47bc-a936-13cb9aca9e05",
      title: "Think Straight: Change your thoughts, Change your life",
      author: " Darius Foroux",
      imgLink: "/images/DatabaseImage/71Yb9hJXocL.jpg",
      price: 1090,
      categoryName: ["Development", "Fiction"],
      description: "Quisque consequat risus id dapibus tincidunt. Praesent consectetur arcu id ornare eleifend.",
      id: 7,
      rating: 3,
  },
  {
      _id: "00f262f1-257d-4a2f-91dc-ec45b32b521b",
      title: "GATE 2024 Electrical Engineering",
      author: "ACE Engineering Academy",
      imgLink: "/images/DatabaseImage/51jc5F0iz4L.jpg",
      price: 6800,
      categoryName: ["Educational"],
      description: "Nam imperdiet lacus a porta facilisis. Etiam semper ante sed metus aliquet cursus.",
      id: 8,
      rating: 1,
  },
  {
      _id: "4f1301fa-516d-4ac9-8487-6554951ad9c6",
      title: "Harry Potter Box Set: The Complete Collection",
      author: "J.K. Rowling",
      imgLink: "/images/DatabaseImage/81zqe4fNdlL.jpg",
      price: 10000,
      categoryName: ["Fiction", "Crime"],
      description: "Curabitur fringilla sem eu nisi tincidunt scelerisque. Nulla ut sapien vel urna facilisis placerat ac id enim.",
      id: 9,
      rating: 3,
  },
  {
      _id: "373cb888-a7a2-4d6a-b138-109ee252a6e3",
      title: "The Complete Novels of Sherlock Holmes",
      author: "Arthur Conan Doyle",
      imgLink: "/images/DatabaseImage/71WZEX98qdL.jpg",
      price: 2500,
      categoryName: ["Fiction", "Development"],
      description: "Fusce faucibus est vitae dictum blandit. Ut porttitor lacus a augue suscipit, id egestas eros rutrum.",
      id: 10,
      rating: 2.7
  },
  {
      _id: "e2f55b19-eecd-451d-84d6-9e6ebaa1ec8c",
      title: "JAVA: THE COMPLETE REFERENCE ,12TH EDITION",
      author: "Herbert Schildt ",
      imgLink: "/images/DatabaseImage/71AF8eZ5A5L.jpg",
      price: 10000,
      categoryName: ["Educational", "Crime", "Fiction"],
      description: "Quisque vitae ipsum nec sapien facilisis volutpat eu at est. In rhoncus libero eu egestas rhoncus.",
      id: 11,
      rating: 2.5
  },
  {
      _id: "c40f8f2e-6169-4113-8840-b56d96d93f43",
      title: "Don't Believe Everything You Think",
      author: " Joseph Nguyen",
      imgLink: "/images/DatabaseImage/716w5Xpj8L.jpg",
      price: 2900,
      categoryName: ["Development"],
      description: "Pellentesque consectetur felis eu libero condimentum commodo quis sit amet purus.",
      id: 12,
      rating: 4,
  },
  {
      _id: "1cd04721-ca67-4918-9413-fdd194474505",
      title: "Death Beyond Forbidding Gates",
      author: "Sarah Pinborough ",
      imgLink: "/images/DatabaseImage/51j6rhjFL6S.jpg",
      price: 5930,
      categoryName: ["Crime", "Development"],
      description: "Nulla vitae metus id mauris iaculis lacinia ut semper augue. Proin et velit eget leo tempor bibendum.",
      id: 13,
      rating: 1.5
  },
  {
      _id: "70b6650a-ad00-49f7-8b96-99937dfe9af6",
      title: "Rich Dad Poor Dad",
      author: " Robert T. Kiyosaki",
      imgLink: "/images/DatabaseImage/81BE7eeKzAL.jpg",
      price: 6000,
      categoryName: ["Development", "Fiction"],
      description: "Suspendisse vulputate justo ut lorem rutrum, sed mollis quam ultrices.",
      id: 14,
      rating: 3.5
  },
  {
      _id: "1e2be37f-2150-43ef-bd63-389e0bdaefd2",
      title: "Night Train at Deoli and Other Stories",
      author: "Ruskin Bond ",
      imgLink: "/images/DatabaseImage/81APABLp4wS.jpg",
      price: 4050,
      categoryName: ["Fiction", "Crime"],
      description: "In viverra diam vitae consectetur iaculis.",
      id: 15,
      rating: 3.5
  },
  {
      _id: "3dbb3085-ed9a-4cb1-aada-80b2e29025e7",
      title: "Gates' Bookstore: 1",
      author: "Jamila A Stone",
      imgLink: "/images/DatabaseImage/61DWEmqBkeL.jpg",
      price: 9000,
      categoryName: ["Crime", "Development"],
      description: "Vivamus porttitor orci in justo faucibus congue.",
      id: 16,
      rating: 1.8
  }
];